// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// consistent_frechet_cpp
Rcpp::List consistent_frechet_cpp(const arma::vec& x);
RcppExport SEXP _frechetAEE_consistent_frechet_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(consistent_frechet_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// ce_frechet_cpp
Rcpp::List ce_frechet_cpp(const arma::vec& x);
RcppExport SEXP _frechetAEE_ce_frechet_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ce_frechet_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// sumAbsPairwiseDiff
double sumAbsPairwiseDiff(const arma::vec& x);
RcppExport SEXP _frechetAEE_sumAbsPairwiseDiff(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sumAbsPairwiseDiff(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_frechetAEE_consistent_frechet_cpp", (DL_FUNC) &_frechetAEE_consistent_frechet_cpp, 1},
    {"_frechetAEE_ce_frechet_cpp", (DL_FUNC) &_frechetAEE_ce_frechet_cpp, 1},
    {"_frechetAEE_sumAbsPairwiseDiff", (DL_FUNC) &_frechetAEE_sumAbsPairwiseDiff, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_frechetAEE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
