# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

consistent_frechet_cpp <- function(x) {
    .Call('_frechetAEE_consistent_frechet_cpp', PACKAGE = 'frechetAEE', x)
}

ce_frechet_cpp <- function(x) {
    .Call('_frechetAEE_ce_frechet_cpp', PACKAGE = 'frechetAEE', x)
}

sumAbsPairwiseDiff <- function(x) {
    .Call('_frechetAEE_sumAbsPairwiseDiff', PACKAGE = 'frechetAEE', x)
}

